<h1>Logs</h1>

<p><a href="/ticket/new">new</a></p>
<div id="react-root"></div>
<table class="pure-table">
    <tr>
        <th>Title</th>
        <th>Component</th>
        <th>Description</th>
        <th>Actions</th>
    </tr>

<?php foreach ($data as $val): ?>

    <tr>
        <td><?=$val?></td>
    </tr>

<?php endforeach; ?>
</table>

<script src="http://localhost:8080/dist/bundle.js"></script>
